Fix/financial services without bank
energialy/energialy-app pull request #183
Opened 2024-04-09 23:52 UTC by FSamayoa

comparto para validarlo.

Saludos.

2024-04-10 22:51 UTC, juancruzroldan95 requested changes
@FSamayoa Hola Fer! Te dejé unos comentarios, cualquier cosa avisame. Gracias!!

2024-04-10 22:51 UTC, juancruzroldan95 commented on client/src/app/dashboard/components/MenuItem.jsx
@FSamayoa veo que el `if else` hace lo mismo en ambos casos, podríamos sacar el condicional en este caso no?
Por otro lado, por favor también borremos los comentarios así dejamos el código limpio.
Gracias!

2024-04-10 22:51 UTC, juancruzroldan95 commented on client/src/app/components/hello.jsx
@FSamayoa este archivo nuevo lo veo vacío, se podrá borrar?

2024-04-11 00:27 UTC, FSamayoa commented on client/src/app/components/hello.jsx
ok, los cancelo hago los cambios y lo mando de nuevo

2024-04-11 00:28 UTC, FSamayoa commented
Se cancela y se mandara de nuevo con los cambios.

2024-04-11 00:28 UTC, closed without merging