Fix/solutions some error and warning
energialy/energialy-app pull request #184
Opened 2024-04-10 07:08 UTC by Cemb93

solucionando algunos errores y warning

2024-04-10 22:59 UTC, juancruzroldan95 requested changes
@Cemb93 Hola Carlos como estás? Te dejé unos comentarios. Por favor siempre subamos el código sin partes comentadas. Si hay algo que se tenga que borrar, se borra, no se comenta. Si queremos recuperar código borrado, lo revisamos en el historial de GitHub.

También si queremos agregar comentarios explicando lo que hace cierta parte del código para nuestros compañeros, lo escribimos en el PR de GitHub, no como un comentario en el código fuente.

Gracias!!

2024-04-10 22:59 UTC, juancruzroldan95 commented on client/src/app/components/DashboardTableData.jsx
> +                  {/* // ! ERROR SOLUCIONADO */}
@Cemb93 podremos borrar los comments? Así queda el código limpio. Gracias!

2024-04-10 22:59 UTC, juancruzroldan95 commented on client/src/app/components/LocationFilter.jsx
> +        // ! ERROR SOLUCIONADO
@Cemb93 Aquí lo mismo, se podrá borrar el comment? Gracias!

2024-04-10 22:59 UTC, juancruzroldan95 commented on client/src/app/dashboard/components/CompanyDashboard.jsx
> +    // fetch(`${process.env.NEXT_PUBLIC_BASE_URL}/users?email=${user.email}`)
@Cemb93 Aquí también, los PRs los subimos sin código comentado.

2024-04-10 22:59 UTC, juancruzroldan95 commented on client/src/app/dashboard/components/SideBar.jsx
> +        // const result = await bankAccountOpen(user.company.id);
@Cemb93 Aquí lo mismo

2024-04-12 01:23 UTC, closed without merging

2024-04-12 01:24 UTC, Cemb93 commented
se cancela el PR