Feature/chat
energialy/energialy-app pull request #228
Opened 2024-05-28 23:15 UTC by JoseValperga

2024-05-28 23:50 UTC, juancruzroldan95 commented
@JoseValperga Hola José! Te dejé unos comentarios.

Adicional, cada vez que el input tiene un cambio, se muestra un `console.log()`, podemos sacarlo?
![image](https://github.com/energialy/energialy-app/assets/110354500/2ee9bc4c-7136-46b4-9e8e-aa24229ef609)

En el detalle de una company, al abrir el chat y escribir, no puedo subrayar el texto con el mouse porque se me mueve la caja (entiendo que esto es por React Draggable _- no entiendo su funcionalidad aquí - _). También habría que sacar las companies que aparecen en rectangulos negros.
![image](https://github.com/energialy/energialy-app/assets/110354500/4acec0ad-2457-4c22-8929-468418a94c0d)

2024-05-28 23:50 UTC, juancruzroldan95 requested changes

2024-05-28 23:50 UTC, juancruzroldan95 commented on api/src/server.js
Qué le pasó a este archivo que está todo comentado?

2024-05-28 23:50 UTC, juancruzroldan95 commented on client/src/app/dashboard/components/CompanyDashboard.jsx
> +      <div className="flex items-center p-2 text-6xl text-gray-400 font-extralight font-jose">
Este sigue con el texto en `6xl`, por favor mantenerlo en `text-xl`

2024-05-28 23:50 UTC, juancruzroldan95 commented on client/src/app/directory/[id]/page.jsx
> +*/
Todo esto que está comentado que es? Si no se va a usar borremoslo porfa 🙏

2024-05-29 13:33 UTC, JoseValperga commented on client/src/app/directory/[id]/page.jsx
> +*/
Lo deje de ayuda para hacer los filtros del chat

2024-05-29 13:34 UTC, JoseValperga commented on client/src/app/dashboard/components/CompanyDashboard.jsx
> +      <div className="flex items-center p-2 text-6xl text-gray-400 font-extralight font-jose">
Listo

2024-05-29 13:38 UTC, JoseValperga commented on api/src/server.js
Listo, ya saqué el console.log que estorbaba y el draggable

2024-05-29 13:38 UTC, JoseValperga commented on client/src/app/directory/[id]/page.jsx
> +*/
Ya lo saqué

2024-05-29 13:44 UTC, JoseValperga commented on api/src/server.js
Los botones negros son provisorios mientras continuo con el desarrollo del chat. Van a estar solo en el chat multimpresa, no así en el privado empresa/empresa. Sucede que los dos comparten archivos de mensajes, motivo por el cual se renderiza en los dos chats.

2024-05-29 13:46 UTC, JoseValperga commented on api/src/server.js
Ahora saco los comentarios de server.js Los dejé como ayuda cuando estuve profundizando SocketIo, ya que era la primera vez que estudiaba ese tema.

2024-05-29 13:47 UTC, JoseValperga commented on api/src/server.js
Los comentarios que viste al principio corresponden al server anterior al chat completo. Lo dejé allí por las dudas antes de hacer los cambios que necesitaba. Ya los retiré

2024-05-31 17:55 UTC, juancruzroldan95 commented
Hola @JoseValperga veo conflictos en el PR y por eso no se puede mergear, cuando puedas resolvelos y mergeá el PR

2024-06-03 14:34 UTC, juancruzroldan95 approved these changes

2024-06-03 14:35 UTC, merged